import { spawnSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';

const backend = fileURLToPath(new URL('../../backend/', import.meta.url));
const venvPython = join(backend, '.venv', process.platform === 'win32' ? 'Scripts/python.exe' : 'bin/python');
const python = process.env.PYTHON || (existsSync(venvPython) ? venvPython : 'python');
const exported = spawnSync(python, ['-c',
  'import json; from app.config import Settings; from app.main import create_app; print(json.dumps(create_app(Settings(_env_file=None)).openapi()))'
], { cwd: backend, encoding: 'utf8' });
if (exported.error) throw exported.error;
if (exported.status !== 0) throw new Error('OpenAPI export failed: ' + exported.stderr);
const schema = JSON.parse(exported.stdout);
const output = '/** Generated by npm run types:generate. Do not edit. */\n' + astToString(await openapiTS(schema));
const destination = new URL('../src/api/generated.ts', import.meta.url);
if (process.argv.includes('--check')) {
  let existing = '';
  try { existing = await readFile(destination, 'utf8'); } catch {}
  if (existing !== output) throw new Error('API types drifted. Run npm run types:generate and review the diff.');
  console.log('API types match current FastAPI OpenAPI');
} else {
  await writeFile(destination, output);
  console.log('Generated src/api/generated.ts');
}
